import tkinter
tk = tkinter.Tk()
tk.title ('Calculator')
tk.geometry('260x216')
txt1 = tkinter.Text(tk, wrap='none')
txt1.tag_config('justified',justify='right')
txt1.tag_add('justified','1.0','end')
txt1.pack()
txt1.place(x=10,y=10,height=30,width=240)

def enterText(textToEnter):
    for i in txt1.get('1.0','end'):
        if i == '.' and textToEnter == '.':
            return None
    txt1.insert(2.0,chars=textToEnter)
    txt1.tag_add('justified','1.0','end')
    
def storeV1(sign):
    global v1
    v1 = float(txt1.get('1.0','end'))
    global f
    f = sign
    txt1.delete('1.0','end')
    
def solve():
    global v2
    v2 = float(txt1.get('1.0','end'))
    s = str(v1) + f + str(v2)
    txt1.delete('1.0','end')
    txt1.insert('1.0',eval(s),'end')
    txt1.tag_add('justified','1.0','end')
    
equalto= tkinter.Button(tk,text='=',command=lambda:solve())
equalto.pack()
equalto.place(x=160,y=130,height=70,width=90)
plus = tkinter.Button(tk,text='+',command=lambda:storeV1('+'))
plus.pack()
plus.place(x=160,y=50,height=30,width=40)
minus = tkinter.Button(tk,text='-',command=lambda:storeV1('-'))
minus.pack()
minus.place(x=160,y=90,height=30,width=40)
multi = tkinter.Button(tk,text='x',command=lambda:storeV1('*'))
multi.pack()
multi.place(x=210,y=50,height=30,width=40)
div = tkinter.Button(tk,text='/',command=lambda:storeV1('/'))
div.pack()
div.place(x=210,y=90,height=30,width=40)
clear = tkinter.Button(tk,text='CLEAR',command=lambda:txt1.delete('1.0','end'))
clear.pack()
clear.place(x=110,y=170,height=30,width=40)
b9 = tkinter.Button(tk,text='9',command=lambda:enterText('9'))
b9.pack()
b9.place(x=110,y=50,height=30,width=40)
b8 = tkinter.Button(tk,text='8',command=lambda:enterText('8'))
b8.pack()
b8.place(x=60,y=50,height=30,width=40)
b7 = tkinter.Button(tk,text='7',command=lambda:enterText('7'))
b7.pack()
b7.place(x=10,y=50,height=30,width=40)
b6 = tkinter.Button(tk,text ='6',command=lambda:enterText('6'))
b6.pack()
b6.place(x=110,y=90,height=30,width=40)
b5 = tkinter.Button(tk,text='5',command=lambda:enterText('5'))
b5.pack()
b5.place(x=60,y=90,height=30,width=40)
b4 = tkinter.Button(tk,text='4',command=lambda:enterText('4'))
b4.pack()
b4.place(x=10,y=90,height=30,width=40)
b3 = tkinter.Button(tk,text='3',command=lambda:enterText('3'))
b3.pack()
b3.place(x=110,y=130,height=30,width=40)
b2 = tkinter.Button(tk,text='2',command=lambda:enterText('2'))
b2.pack()
b2.place(x=60,y=130,height=30,width=40)
b1 = tkinter.Button(tk,text='1',command=lambda:enterText('1'))
b1.pack()
b1.place(x=10,y=130,height=30,width=40)
b0 = tkinter.Button(tk,text='0',command=lambda:enterText('0'))
b0.pack()
b0.place(x=10,y=170,height=30,width=40)
point = tkinter.Button(tk,text='.',command=lambda:enterText('.'))
point.pack()
point.place(x=60,y=170,height=30,width=40)
tk.mainloop()